yarnPath: ".yarn/releases/yarn-berry.cjs"

# disabling this is for development and ci only as it makes ci jobs fail
# in production, we should use YARN_ENABLE_SCRIPTS=true when we build in order to get optimizations provided by postInstall scripts
enableScripts: false
